[build]
  functions = "functions"

[dev]
  functions = "functions"
  framework = "vite"
  targetPort = 5173

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
